def get_bank_name(bank_code):
    banks = {
        '01': 'KCB Bank Kenya',
        '02': 'Standard Chartered Kenya',
        '03': 'Barclays Bank of Kenya (Absa)',
        '06': 'Bank of Baroda Kenya Limited',
        '07': 'NCBA Bank Kenya',
        '09': 'Equity Bank Kenya',
        '10': 'Prime Bank Limited',
        '11': 'Co-operative Bank of Kenya Ltd',
        '12': 'National Bank of Kenya Ltd',
        '13': 'Citi Bank Kenya',
        '14': 'M-Oriental Bank Ltd',
        '16': 'Citibank NA',
        '17': 'Habib Bank Limited',
        '18': 'Middle East Bank Kenya Ltd',
        '19': 'Bank of Africa Kenya Ltd',
        '20': 'Bank of Africa Kenya',
        '21': 'Consolidated Bank of Kenya',
        '23': 'Consolidated Bank of Kenya Ltd',
        '24': 'Dubai Bank Kenya',
        '25': 'Credit Bank Limited',
        '26': 'Access Bank Kenya',
        '27': 'Imperial Bank Kenya',
        '28': 'Paramount Bank',
        '29': 'Trans National Bank Kenya',
        '30': 'UBA Kenya',
        '31': 'Victoria Commercial Bank',
        '33': 'Chase Bank Kenya',
        '34': 'Ecobank Kenya',
        '35': 'African Banking Corporation Ltd',
        '39': 'Jamil Bora Bank',
        '40': 'Kingdom Bank',
        '41': 'M-Oriental Bank',
        '42': 'Mayfair Bank',
        '43': 'Ecobank Kenya Limited',
        '48': 'Caritas Microfinance Bank',
        '50': 'Paramount Universal Bank Ltd',
        '51': 'Kingdom Bank',
        '53': 'Guaranty Trust Bank Kenya',
        '54': 'Victoria Commercial Bank Ltd',
        '55': 'Guardian Bank Ltd',
        '57': 'I & M Bank Kenya Ltd',
        '59': 'Development Bank of Kenya Ltd',
        '60': 'SBM Bank Kenya',
        '61': 'Housing Finance Cooperation Kenya (HFC Bank)',
        '62': 'PostBank Kenya',
        '63': 'Diamond Trust Bank Kenya Ltd',
        '65': 'Commercial International Bank',
        '66': 'Sidian Bank Kenya',
        '67': 'UMBA Microfinance Bank',
        '68': 'Equity Bank Kenya Ltd',
        '70': 'Family Bank Ltd',
        '72': 'Gulf African Bank Ltd',
        '74': 'Premier Bank Kenya',
        '75': 'Dubai Islamic Bank Ltd',
        '76': 'UBA Kenya Bank Ltd',
        '78': 'Kenya Women Microfinance Bank',
        '79': 'Faulu Microfinance Bank',
        '82': 'Choice Microfinance Bank',
        '89': 'Stima Sacco',
        '93': 'Vooma',
        '97': 'Telkom Kenya',
        '138': 'NCBA Loop',
    }

    return banks.get(str(bank_code).strip(), 'Unknown Bank')
