# Generated by Django 5.2.7 on 2026-01-20 17:03

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=webapp.models.generate_order_id, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
