# Generated by Django 5.2.7 on 2026-01-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_contract_completed_date_contract_is_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('contract_completed', 'Contract Completed'), ('rating_received', 'Rating Received'), ('payment_received', 'Payment Received'), ('task_assigned', 'Task Assigned')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='webapp.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
