# Generated by Django 5.2.7 on 2025-11-26 13:42

import django.db.models.deletion
import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_user_wallet_balance_paymentrecord_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerrating',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='freelancerrating',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='freelancerrating',
            name='task',
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('repo_url', models.URLField(blank=True, null=True)),
                ('commit_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('staging_url', models.URLField(blank=True, null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('apk_download_url', models.URLField(blank=True, null=True)),
                ('testflight_link', models.URLField(blank=True, null=True)),
                ('admin_username', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_password', models.CharField(blank=True, max_length=100, null=True)),
                ('access_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revisions_requested', 'Revisions Requested')], default='submitted', max_length=20)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to=webapp.models.Submission.submission_files_path)),
                ('screenshots', models.FileField(blank=True, null=True, upload_to=webapp.models.Submission.submission_files_path)),
                ('video_demo', models.FileField(blank=True, null=True, upload_to=webapp.models.Submission.submission_files_path)),
                ('deployment_instructions', models.TextField(blank=True, null=True)),
                ('test_instructions', models.TextField(blank=True, null=True)),
                ('release_notes', models.TextField(blank=True, null=True)),
                ('checklist_tests_passing', models.BooleanField(default=False)),
                ('checklist_deployed_staging', models.BooleanField(default=False)),
                ('checklist_documentation', models.BooleanField(default=False)),
                ('checklist_no_critical_bugs', models.BooleanField(default=False)),
                ('revision_notes', models.TextField(blank=True, null=True)),
                ('resubmitted_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.contract')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.task')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_type', models.CharField(choices=[('employer_to_freelancer', 'Employer to Freelancer'), ('freelancer_to_employer', 'Freelancer to Employer')], max_length=25)),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='webapp.user')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='webapp.user')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.task')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.submission')),
            ],
            options={
                'unique_together': {('task', 'rater', 'rated_user')},
            },
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.submission'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployerRating',
        ),
        migrations.DeleteModel(
            name='FreelancerRating',
        ),
    ]
