# Generated by Django 5.2.7 on 2025-12-28 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_employerprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField( 
    model_name='employerprofile',
    name='profession',
    field=models.CharField(max_length=100, blank=True, null=True),
),
        migrations.RemoveField(
            model_name='employerprofile',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='id_number',
            field=models.CharField(blank=True, help_text="National ID, Passport or Driver's License number", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='notification_preferences',
            field=models.JSONField(default=dict, help_text="User's notification preferences"),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='address',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell about yourself and what services you need', null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='city',
            field=models.CharField(default='Not provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='contact_email',
            field=models.EmailField(default='not-provided@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='full_name',
            field=models.CharField(default='Not provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='phone_number',
            field=models.CharField(default='Not provided', max_length=20),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payments', to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_payments', to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='webapp.user'),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['contact_email'], name='webapp_empl_contact_de5dba_idx'),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['phone_number'], name='webapp_empl_phone_n_270396_idx'),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['verification_status'], name='webapp_empl_verific_54742b_idx'),
        ),
    ]
