# Generated by Django 5.2.7 on 2026-01-05 13:25

from django.db import migrations
def fix_missing_freelancers(apps, schema_editor):
    Order = apps.get_model('webapp', 'Order')
    Freelancer = apps.get_model('webapp', 'Freelancer')
    User = apps.get_model('auth', 'User')

    # Get or create a default freelancer
    default_user = User.objects.first()  # assumes you have at least one user
    if not default_user:
        raise Exception("No User exists. Create a user before running this migration.")

    default_freelancer, _ = Freelancer.objects.get_or_create(user=default_user)

    # Assign all orders with missing freelancer
    orders = Order.objects.filter(freelancer__isnull=True)
    for order in orders:
        order.freelancer = default_freelancer
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_order_options_alter_order_employer_and_more'),
    ]

    operations = [
    ]
