# Generated by Django 5.2.7 on 2026-01-05 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_fix_missing_freelancers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='paystack_subaccount_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='task',
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='webapp.freelancer'),
        ),
    ]
