# Generated by Django 5.2.7 on 2026-01-05 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_order_options_remove_freelancer_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='webapp.employer'),
        ),
    ]
