# Generated by Django 5.2.7 on 2026-01-05 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_order_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='webapp.task'),
        ),
    ]
