# Generated by Django 5.2.7 on 2026-01-06 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_order_task'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('task', 'rater', 'rated_user')},
        ),
        migrations.AddField(
            model_name='rating',
            name='rater_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given_as_employer', to='webapp.employer'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('task', 'rater', 'rated_user'), ('task', 'rater_employer', 'rated_user')},
        ),
    ]
