# Generated by Django 5.2.7 on 2026-01-08 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_rating_unique_together_rating_rater_employer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('paystack_recipient_code', models.CharField(max_length=100)),
                ('paystack_transfer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved - Processing'), ('processing', 'Being Processed by Paystack'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='freelancer',
            options={'ordering': ['user__name'], 'verbose_name': 'Freelancer', 'verbose_name_plural': 'Freelancers'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='employer',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='account_name',
            field=models.CharField(blank=True, help_text='Account holder name as registered with bank', max_length=255),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=20),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='bank_code',
            field=models.CharField(blank=True, help_text="Paystack bank code (e.g., '058' for GTBank, '031' for Equity)", max_length=10),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='bank_name',
            field=models.CharField(blank=True, help_text="Bank name (e.g., 'Equity Bank')", max_length=100),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='business_name',
            field=models.CharField(blank=True, help_text="Business/Display name for Paystack (e.g., 'John Doe Freelancing')", max_length=255),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='is_paystack_setup',
            field=models.BooleanField(default=False, help_text='True when freelancer has completed Paystack setup'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='last_payout_date',
            field=models.DateTimeField(blank=True, help_text='Last successful payout date', null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='paystack_setup_date',
            field=models.DateTimeField(blank=True, help_text='When Paystack account was created', null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, help_text='Paystack Subaccount Code (starts with ACCT_). Save this after creating subaccount.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='pending_payout',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount pending payout', max_digits=10),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount earned by freelancer', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_transactions', to='webapp.user'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.contract'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_transactions', to='webapp.freelancer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='freelancer_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paystack_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paystack_transfer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.task'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment from Client'), ('withdrawal', 'Withdrawal to Freelancer'), ('refund', 'Refund to Client'), ('commission', 'Platform Commission')], default='payment', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['paystack_reference'], name='webapp_tran_paystac_d77601_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='webapp_tran_transac_42dc21_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['freelancer', 'created_at'], name='webapp_tran_freelan_186a74_idx'),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.freelancer'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.transaction'),
        ),
    ]
