# Generated by Django 5.2.7 on 2026-01-11 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_withdrawalrequest_alter_freelancer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('client_quote', models.TextField(blank=True, null=True)),
                ('completion_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='webapp.user')),
                ('skills_used', models.ManyToManyField(blank=True, related_name='portfolio_pieces', to='webapp.skill')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_rating', models.IntegerField(blank=True, null=True)),
                ('client_feedback', models.TextField(blank=True)),
                ('completion_date', models.DateField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='webapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('self_reported', 'Self-Reported'), ('test_passed', 'Platform Test Passed'), ('verified', 'Portfolio Verified')], default='self_reported', max_length=20)),
                ('verification_evidence', models.URLField(blank=True, null=True)),
                ('date_verified', models.DateField(blank=True, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_skills', to='webapp.user')),
            ],
            options={
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
