# Generated by Django 5.2.7 on 2026-01-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_skill_portfolioitem_workhistory_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='category_scores',
            field=models.JSONField(blank=True, help_text='Per-category rating breakdown', null=True),
        ),
    ]
