# Generated by Django 5.2.7 on 2026-01-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_rating_category_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='calculated_composite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='performance_tags',
            field=models.JSONField(blank=True, help_text='List of performance tags', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='would_recommend',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='would_rehire',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
