# Generated by Django 5.2.7 on 2026-01-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_rating_calculated_composite_rating_performance_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='amount_held_in_escrow',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='task_files/'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('escrowed', 'Held in Escrow by Helawork'), ('released', 'Paid to Worker'), ('refunded', 'Refunded to Employer')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='payment_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='service_type',
            field=models.CharField(choices=[('remote', 'Remote (Digital Online Work)'), ('on_site', 'On-Site (Physical Work)')], default='remote', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('digital_marketing', 'Digital Marketing'), ('cleaning', 'Cleaning & Housekeeping'), ('handyman', 'Handyman & Repairs'), ('delivery', 'Delivery Services'), ('moving', 'Moving & Packing'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('awaiting_confirmation', 'Awaiting Employer Confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=25),
        ),
    ]
