# Generated by Django 5.2.7 on 2026-01-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_task_amount_held_in_escrow_task_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='service_type',
            field=models.CharField(choices=[('remote', 'Remote (Digital Online Work)'), ('on_site', 'On-Site (Physical Work)')], max_length=20),
        ),
    ]
