# Generated by Django 5.2.7 on 2026-01-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='onsite_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_code',
            field=models.CharField(blank=True, help_text='OTP for onsite tasks', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('escrowed', 'Held in Escrow by Platform'), ('released', 'Paid to Worker'), ('refunded', 'Refunded to Employer')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('awaiting_payment', 'Awaiting Payment'), ('in_progress', 'In Progress'), ('awaiting_confirmation', 'Awaiting Employer Confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=25),
        ),
    ]
