# Generated by Django 5.2.7 on 2026-01-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_task_onsite_verified_at_task_verification_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('mobile', 'Mobile Development'), ('desing', 'Design'), ('digital_marketing', 'Digital Marketing'), ('cleaning', 'Cleaning & Housekeeping'), ('handyman', 'Handyman & Repairs'), ('delivery', 'Delivery Services'), ('moving', 'Moving & Packing'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
