# Generated by Django 5.2.7 on 2026-01-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='bid_amount',
        ),
    ]
