# Generated by Django 5.2.7 on 2026-01-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_remove_proposal_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='completion_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
