# Generated by Django 5.2.7 on 2026-01-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_payment_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
